version: '3.9'
services:
  node:
    image: node
    working_dir: /home/node/app
    env_file:
      - .env
    command: 
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '3003:3003'
    volumes:
      - './src:/home/node/app'
  # mysql:
  #   image: mysq
  #   ports:
  #     - '27017:27017'